apiVersion: v1
kind: Pod
metadata:
  name: 2-toleration-pod-no-execute
spec:
  containers:
  - name: nginx-no-execute
    image: nginx
  tolerations:
  - key: "key"
    operator: "Equal"
    value: "value"
    effect: "NoExecute"