apiVersion: v1
kind: Pod
metadata:
  name: pod-con-affinity-anti-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - minikube-m03
  containers:
  - name: pod-con-affinity-anti-affinity
    image: busybox:latest
    command:
    - sleep
    - "3600"
