apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  # root password: admin123 (base64 encoded)
  mysql-root-password: YWRtaW4xMjM=
  # database name: wordpress (base64 encoded)
  mysql-database: d29yZHByZXNz
  # database user: wpuser (base64 encoded)
  mysql-user: d3B1c2Vy
  # user password: wppass123 (base64 encoded)
  mysql-password: d3BwYXNzMTIz
