apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: default
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Accessible on <node-ip>:30080
    protocol: TCP
  selector:
    app: wordpress
