apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: prueba-con-wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080   # cambiar si ya esta en uso