apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-node01-claim          
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage-2
  resources:
    requests:
      storage: 1Gi             

