apiVersion: v1
kind: Pod
metadata:
  name: simulador-eventos
spec:
  containers:
    - image: kodekloud/event-simulator
      name: simulador-eventos    
      volumeMounts:
        - mountPath: /log
          name: webapp
  volumes:
    - name: webapp
      hostPath:
        # localización del directorio en el host
        path: /var/log/webapp
        # este campo es opcional
        type: Directory