apiVersion: v1
kind: Pod
metadata:
  name: 2-mi-redis
spec:
  containers:
  - name: 2-mi-redis
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: api-secrets