apiVersion: v1
kind: Pod
metadata:
  name: webapp-db
spec:
  containers:
    - name: webapp-db
      image: kodekloud/simple-webapp-mysql
      envFrom:
      - secretRef:
          name: db-secret
    - image: mysql:8.0
      name: sql01
      envFrom:
      - secretRef:
          name: db-secret       
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-pass
            key: password
      - name: MYSQL_DATABASE
        value: wordpress
      - name: MYSQL_USER
        value: wordpress
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-pass
            key: password
      ports:
      - containerPort: 3306
        name: sql01
  restartPolicy: Never