kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: 2-serviceaccount-namespace
  name: backend-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: 2-serviceaccount-namespace
subjects:
- kind: ServiceAccount
  name: backend-serviceaccount
  namespace: 2-serviceaccount-namespace
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io