apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: 2-serviceaccount-namespace
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: 2-serviceaccount-namespace
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80