apiVersion: v1
kind: Pod
metadata:
  name: 1-command-demo
  labels:
    proposito: demostrar-comandos
spec:
  containers:
  - name: 1-command-demo-container
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]