apiVersion: v1
kind: Pod
metadata:
  name: pod-con-topology-spread
spec:
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app: mi-app
  containers:
  - name: pod-con-topology-spread
    image: nginx:latest