apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: pruebas
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disco: ssd # Aqui esta nuestra label