apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
spec:
  volumeMode: Filesystem
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/var/log/webapp"  