apiVersion: v1
kind: Pod
metadata:
  name: pod-con-prioridad
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: prioridad
            operator: In
            values:
            - nivel1
        topologyKey: topology.kubernetes.io/zone
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: prioridad
              operator: In
              values:
              - nivel2
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: pod-con-prioridad
    image: busybox:latest
    command:
    - sleep
    - "3600"