apiVersion: v1
kind: Namespace
metadata:
  name: pod-reader-sayayin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pod-reader-sayayin
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: pod-reader-sayayin
subjects:
- kind: User
  name: goku
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io