apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pod-reader-sayayin
  name: pod-create
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-pods-binding
  namespace: pod-reader-sayayin
subjects:
- kind: User
  name: goku
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-create
  apiGroup: rbac.authorization.k8s.io